config:
  # Configuration for Mode 0 (normal mode)
  modeZero:
    # The calculation time in ticks (20 ticks = 1 second) - no lag (another thread)
    CalcDelayInTicks: 40
    # The update time in ticks (20 ticks = 1 second) - little lag if too low - nothing major
    UpdateDelayInTicks: 40
    
  # Configuration for Mode 1 (3.6 mode)
  modeOne:
    # The update time in 3.6 seconds (x times 3.6 sec) - 1 time is default
    UpdateDelayIn3dot6Seconds: 1
    
  # This will enable the use of PlayerTime instead of changing the real time
  # You can disable that for any player using the permission: realtime.noptime
  usePlayerTime: true
  
  # Mode = 0 = Normal mode - time is calculated and set
  # Mode = 1 = Mode 3.6 - time is calculated ONCE and added after time
  # Mode 1 for +18 TPS servers, or it'll change the time
  ModeBeingUsed: 0
  
  # This will decide if the plugin will automaticly enable when loading
  # You can manually enable/disable using "/realtime start/stop"
  enableOnLoad: true
  
  # This will enable/disable the permissions - even for OPs
  # - This DOENST APPLY for realtime.start/stop/reload! -
  permissionEnabled: false
  
  # This will set if the plugin will correct the config.yml when something goes wrong
  # !! THIS WILL DELETE THIS "# COMMENTS" !!
  enableSelfFixing: true
  
  # This will fix your time in case your server is on another country, for example
  # Like, your city is 8pm, and your server is 9pm, you add 1000 to this and it'll be fixed once you restart
  timeFixInTicks: 0
  
  # The list of NORMAL worlds (NO NETHER OR THE END AVALIABLE)
  # - THE WORLD LIST IS CASE SENSITIVE! -
  # If you set it 'null', or leave it, the plugin will use all NORMAL worlds (not nether or the end).
  # This will probably conflit with MultiWorld plugins, I created a system so you dont need to manually edit the plugin.yml to softdepend
  worldList:
  - world

PVPTime:
  # This will enable or disable your PVPTime compatibility, if you dont enable it, the PVP will be announced more than one time
  enabled: false
  # Ajust with your PVPTime's configuration
  startTime: 500
  endTime: 12500
  
# Leave that...
debug:
  useDebugMode: false
  
  # You can test your server for certain clocks, just enable this (even if useDebugMode is false), set the time and restart
  DebugTime:
    enabled: false
    hour: 0
    min: 0
    sec: 0
