name: RealTime
version: 1.3
author: rfsantos1996
main: com.jabyftw.realtime.RealTime
description: Transform real time to Minecraft time!
permissions:
  realtime.noptime:
    description: 'People wont have their player times changed'
    default: op
  realtime.start:
    description: 'They can do /realtime start'
    default: op
  realtime.stop:
    description: 'They can do /realtime stop'
    default: op
  realtime.reload:
    description: 'They can do /realtime reload'
    default: op