name: RealTime
version: 1.2.1
author: rfsantos1996
main: com.jabyftw.realtime.RealTime
description: Transform real time to Minecraft time!
permissions:
  realtime.noptime:
    description: 'People wont have their player times changed'
    default: op